export const Colors = {
  primaryColor: '#FF9646',
  placeColor: '#FFF5ED',
  brandGray: '#D4D8DB',
  brandGray200: '#AAB1B7',
  textDark: '#343434',
  textWhite: '#FFF',
  disabledColor: '#FFEADA',
  borderPrimaryColor: '#FFAB6B',
  borderColor: '#D7D9DB',
  successsColor: '#46DC9D',
  otpBorder: '#EBECED',
  optFocusBorder: '#FFC090',
  transparent: 'transparent',
  textHeader: '#21272D',
  iconBackground: 'rgba(70, 220, 157, 0.20)',
  textColor: '#0B0D0F',
};
